### PR TITLE
File picker, cxx, apksigner features 

### PR DESCRIPTION
**Pull request by DoubleCai**
[*]Bug fix: LIBNMMVM_NAME replace failed.
[*]Bug fix: Config RegisterNativesClassName is invalid.

### CODE REVIEW

**Comment by timscriptov** [comment]
Hello, I just saw your pull request today.

**Comment by DoubleCai** [comment]
Just committed some features, not bug fix. :(

**Comment by timscriptov** [comment]
Thanks

**Comment by timscriptov** [comment]
Project structure updated

**Pull request merged**
